version: '3.8'

services:
  app:
    build: .
    env_file: .env
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    networks:
      - price-alert-network
    volumes:
      - ./logs:/app/logs

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: price_alert_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - price-alert-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - price-alert-network
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:

networks:
  price-alert-network:
